'no-empty': 'error'
kamilkisiela/graphql-inspector pull request #2229
Opened 2023-01-05 10:07 UTC by TuvalSimha

2023-01-10 09:38 UTC, B2o5T commented on packages/commands/introspect/__tests__/introspect-command.spec.ts
> +    }
```suggestion
    } catch {
      /* ignore */
    }
```

2023-01-10 09:38 UTC, B2o5T commented on packages/github/src/helpers/diff.ts
> +// eslint-disable-next-line n/no-restricted-import
```suggestion
// eslint-disable-next-line n/no-restricted-import -- todo: replace in next major
```

2023-01-10 09:39 UTC, B2o5T commented on packages/github/src/helpers/diff.ts
> +// eslint-disable-next-line n/no-restricted-import
or can you replace `axios` here also? since you replaced in other file

2023-01-10 09:40 UTC, B2o5T commented on packages/github/src/helpers/loaders.ts
> +  const introspection = data.json();
```suggestion
  const introspection = await data.json();
```

2023-01-10 09:40 UTC, B2o5T commented on packages/github/src/helpers/loaders.ts
> +    buildClientSchema(await introspection, {
```suggestion
    buildClientSchema(introspection, {
```

2023-01-10 09:41 UTC, B2o5T commented on scripts/release.js
> +import axios from 'axios';
can you replace `axios` here also?

2023-01-10 09:43 UTC, B2o5T commented on .eslintrc.cjs
> +        '@typescript-eslint/no-var-requires': 'error',
no need to put error, they are already in config, you should remove them

2023-01-10 09:44 UTC, B2o5T commented on .eslintrc.cjs
> +        '@typescript-eslint/no-var-requires': 'error',
```suggestion
```

2023-01-10 09:44 UTC, B2o5T commented on .eslintrc.cjs
> +        '@typescript-eslint/no-empty-function': 'error',
```suggestion
```

2023-01-10 09:44 UTC, B2o5T commented on .eslintrc.cjs
> +        'n/no-restricted-import': 'error',
```suggestion
```

2023-01-10 09:47 UTC, B2o5T requested changes
I left suggestions, also let's fix the following rules
`no-prototype-builtins`, `no-implicit-coercion` and `no-restricted-syntax`

2023-01-30 17:04 UTC, TuvalSimha commented
@B2o5T 
For this moment, we will ignore this `axios` import, i just open new issue to use fetch from Arda library - https://github.com/ardatan/whatwg-node
I will work on this issue during current sprint.

Issue:
https://github.com/kamilkisiela/graphql-inspector/issues/2261

2023-02-07 14:18 UTC, merged