feat: Rules in Github Action
kamilkisiela/graphql-inspector pull request #2266
Opened 2023-01-31 21:53 UTC by Tohaker

🚨 **IMPORTANT: Please do not create a Pull Request without creating an issue first.**

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._

## Description

This PR actually does the thing.
Adds two new options to the action; `rules` and `onUsage`, to keep wording with the CLI consistent. The `rules` accepts a multi-line list of rules, both built-in and custom, that work exactly the same way as on the CLI. `onUsage` is included too for completeness.

Fixes #2250

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

I'm aware there aren't unit tests for the action yet, but I added an extra test of this to the `actions` workflow as a smoke test

## Checklist:

- [ ] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-15 12:31 UTC, TuvalSimha requested changes
@Tohaker  Rebase and fix the conflicts, i will merge it after that :)

2023-02-15 13:51 UTC, TuvalSimha commented
@Tohaker Can you make sure the CI passes please?  probably lint/prettier

2023-02-22 10:15 UTC, Tohaker commented
@TuvalSimha should be all ready for review again

2023-02-27 11:33 UTC, TuvalSimha approved these changes

2023-02-27 11:33 UTC, merged